security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        utilisateurs_en_memoire:
            memory: 
              users:
                  admin:
                      password: '%env(ADMIN_PASSWORD_HASH)%'
                      roles: ['ROLE_ADMIN']
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt)/
            security: false
        main:
            lazy: true
            stateless: true
            provider: utilisateurs_en_memoire
            http_basic:
                realm: Vigie

    access_control:
        - { path: ^/api, methods: [POST, PUT, PATCH, DELETE], roles: ROLE_ADMIN }