### Créer une ressource
POST http://localhost:8000/api/ressources
Content-Type: application/json

{
    "titre": "",
    "url": "htps://docs.phpunit.de/",
    "categorieId": 1
}

### Modifier une ressource
PUT http://localhost:8000/api/ressources/1
Content-Type: application/json

{
    "titre": "Documentation de référence officielle de Symfony",
    "url": "https://www.php.net/manual/fr/",
    "categorieId": 1
}

### Supprimer une ressource
DELETE http://localhost:8000/api/ressources/12